name: Commitly build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up cx_Freeze
        run: pip install cx_Freeze
      
      - name: Install tkinter (Linux)
        if: ${{ matrix.os != 'windows-latest' }}
        run: sudo apt install python3-tk

      # Runs a set of commands using the runners shell
      - name: Use it to package gzslviewer
        run: cxfreeze gzslviewer -c --target-dir build --include-files gzcompat.frag --include-modules=tkinter,tkinter.ttk
      
      - name: Package and upload the executable
        uses: actions/upload-artifact@v2.2.4
        with:
          name: artifact-${{ matrix.os }}
          path: build/
